services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"
    ports:
      - 1883:1883
      - ${PUERTO_MQTTS}:8883
    restart: unless-stopped
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config:/mosquitto/config
      - ./swag/etc/letsencrypt:/var/tmp
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - URL=${DOMINIO}
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - SUBDOMAINS=
    volumes:
      - ./swag:/config
    ports:
      - ${PUERTO}:443/tcp
      - 80:80
    restart: unless-stopped
  telegrambot:
    image: telegrambot
    build:
      context: ./telegrambot
    container_name: telegrambot
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - TB_TOKEN=${TB_TOKEN}
      - TB_AUTORIZADOS=${TB_AUTORIZADOS}
      - MQTT_USR=${MQTT_USR}
      - MQTT_PASS=${MQTT_PASS}
      - PUERTO_MQTTS=${PUERTO_MQTTS}
      - SERVIDOR=${SERVIDOR}
      - ID_DISPOSITIVO=${ID_DISPOSITIVO}
    restart: unless-stopped
volumes:
  portainer_data: