services:
  clientemqtt:
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazará por la env var SERVIDOR defineda en .env
      - TOPICO=${TOPICO}
      - TOPICO_1=${TOPICO_1}
      - TOPICO_2=${TOPICO_2}
    restart: unless-stopped 
